- hosts: localhost
  name: DevOpsRZDTask
  become: yes
  vars:
  tasks:
    - name: Ensure Docker service is running
      become: yes
      service:
        name: docker
        state: started

    - name: Create Docker network for task
      shell: docker network create task

    - name: Start Node Exporter container
      docker_container:
        image: prom/node-exporter:latest
        name: node-exporter
        port: 9100:9100
        state: started
        networks:
          - name: task
        volumes:
          - /sys:/host/sys:ro
          - /proc:/host/proc:ro
          - /:/rootfs:ro
        command: [" --path.procfs=/host/proc --path.rootfs=/rootfs --path.sysfs=/host/sys --collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)"]


    - name: Start Prometheus container
      docker_container:
        image: prom/prometheus:latest
        name: prometheus
        volumes: 
          - ./prometheus:/prometheus
          - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
        state: started
        port: "9090:9090"
        networks:
          - name: task
       # command: [" --storage.tsdb.path=/prometheus --web.console.libraries=/etc/prometheus/console_libraries --web.console.templates=/etc/prometheus/consoles --web.enable-lifecycle"]

    - name: Start Grafana container
      docker_container:
        name: grafana
        image: grafana/grafana:latest
        env:
          - GF_SECURITY_ADMIN_USER=root
          - GF_SECURITY_ADMIN_PASSWORD=root
          - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/var/lib/grafana/dashboards/app-metrics.json
          - GF_USERS_ALLOW_SIGN_UP=true
        port: "3000:3000"
        volumes:
          - ./grafana:/var/lib/grafana
          - ./grafana/backup/etc_conf:/etc/grafana 
          - ./grafana/backup/grafama.db:/var/lib/grafana/grafana.db
        state: started
        networks:
          - name: task

    - name: Start cAdvisor container
      docker_container:
        name: cadvisor
        image: gcr.io/cadvisor/cadvisor:latest
        command: ["--network monitoring  --prometheus_endpoint"]
        volumes:
          - /var/run:/var/run:rw
          - /sys:/sys:ro
          - /:/rootfs:ro
          - /var/lib/docker/:/var/lib/docker:ro
        state: started
        port: "8081:8080"
        networks:
          - name: task

    # - name: Copy Prometheus configuration file
    #   docker_copy:
    #     src: ./promgrafnode/prometheus/prometheus.yml
    #     dest: /etc/prometheus/prometheus.yml
    #     container: prometheus

    # - name: Copy Grafana provisioning datasources configuration
    #   docker_copy:
    #     src: ./grafana/provisioning/datasources
    #     dest: /etc/grafana/provisioning/datasources
    #     container: grafana